[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "8080"
RAILS_ENV = "production"
OPENPROJECT_WEB_PORT = "8080"
OPENPROJECT_HTTPS = "true"
IMAP_ENABLED = "false"
